# Generated by Django 5.1.4 on 2025-01-20 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_booksdetails_user_reviews_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksdetails',
            name='AuthorName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booksdetails',
            name='description',
            field=models.TextField(),
        ),
    ]
