# Generated by Django 5.1.4 on 2025-01-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_booksdetails_authorname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksdetails',
            name='BookName',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
